Repository rochefort-lab/fissa, pull requests merged in 2019-07, with the labels that each got.

#78 DOC: Change DOI to doi and add a space after the colon
  README.rst
Labels: doc, vX.Y.Z Next Patch Release

#53 TST+MAINT: Swap from scipy.misc.imsave to imageio.imwrite
  fissa/tests/test_datahandler_framebyframe.py
  requirements-dev.txt
Labels: tst, vX.Y.0 Next Minor Release

#80 CI: Travis allow fast_finish
  .travis.yml
Labels: ci, vX.Y.Z Next Patch Release

#67 SimCalc release
  README.rst
Labels: doc, vX.Y.Z Next Patch Release

#75 CI script refactor
  .ci/conda_min_version.sh
  .ci/test_notebooks.sh
  .travis.yml
Labels: ci, vX.Y.Z Next Patch Release

#79 DOC: Fix GPL version mentioned in documentation
  LICENSE
  README.rst
Labels: doc, vX.Y.Z Next Patch Release

#76 DOC: Add our URLs to setup.py metadata
  setup.py
Labels: doc, vX.Y.Z Next Patch Release

#77 DOC: Retitle API section of docs to be API Reference, and tidy up conf.py
  docs/conf.py
Labels: doc, vX.Y.Z Next Patch Release
