Repository rochefort-lab/fissa, pull requests merged in 2021-06, with the labels that each got.

#152 Update .gitignore and .gitattributes
  .gitattributes
  .gitignore
Labels: maint

#153 DOC: Minor README updates
  README.rst
Labels: bug, doc

#154 CI: Add tests with GitHub Actions
  .github/workflows/docs.yaml
  .github/workflows/system_info.py
  .github/workflows/test-release-candidate.yaml
  .github/workflows/test.yaml
  docs/conf.py
  docs/requirements.txt
  fissa/readimagejrois.py
Labels: bug, ci, doc

#157 DOC: Fix docs preventing docs from building
  docs/requirements.txt
  fissa/__meta__.py
Labels: ci, doc

#158 DOC: Change test badge from Travis to GHA
  README.rst
Labels: doc

#159 CI: Fix travis build
  .travis.yml
Labels: ci

#160 CI: Trim down number of jobs running on Travis and AppVeyor
  .appveyor.yml
  .travis.yml
Labels: ci

#161 DEV: Add basic pre-commit
  .github/workflows/pre-commit.yaml
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.rst
  citation.ris
  docs/index.rst
  requirements-dev.txt
  requirements.txt
  requirements_plots.txt
Labels: ci

#162 DOC: Tidy up docstrings
  fissa/core.py
  fissa/readimagejrois.py
Labels: doc

#163 RF: Tidy up
  fissa/ROI.py
  fissa/core.py
  fissa/readimagejrois.py
  fissa/roitools.py
  fissa/tests/test_datahandler.py
  fissa/tests/test_datahandler_framebyframe.py
Labels: maint

#166 DOC: Add shebang and executable flag to example scripts
  examples/basic_usage.py
  examples/basic_usage_windows.py
Labels: doc

#167 DOC: Fix some docstrings
  fissa/core.py
  fissa/roitools.py
Labels: doc

#168 TST:MNT: Tidy up core test code
  fissa/tests/test_core.py
Labels: maint, test

#171 BUG: Don't needlessly redo prep
  fissa/core.py
Labels: bug

#164 MNT: Use ndarray for all outputs, not list for some
  fissa/core.py
Labels: maint

#156 API: Datahandler now functions as a class
  .travis.yml
  examples/Basic usage.html
  examples/Basic usage.ipynb
  fissa/core.py
  fissa/datahandler.py
  fissa/datahandler_framebyframe.py
  fissa/extraction.py
  fissa/tests/test_core.py
  fissa/tests/test_datahandler_framebyframe.py
  fissa/tests/test_extraction.py
Labels: vX.Y.0 New Minor Release

#173 CI: Stop pushing to coveralls
  .appveyor.yml
  .travis.yml
Labels: ci

#174 MNT: Resolve deprecation warnings
  fissa/core.py
  fissa/extraction.py
  fissa/tests/test_ROI.py
Labels: maint

#175 DOC: Docstring and README improvements
  README.rst
  docs/conf.py
  fissa/ROI.py
  fissa/core.py
  fissa/deltaf.py
  fissa/extraction.py
  fissa/neuropil.py
  fissa/readimagejrois.py
  fissa/roitools.py
  fissa/tests/generate_downsampled_resources.py
  setup.py
Labels: doc

#107 BUG: Allow first diagonal expansion based on initial mask
  fissa/roitools.py
  fissa/tests/test_roitools.py
Labels: bug, vX.Y.0 New Minor Release

#176 BUG: Inaccurate means for float16 TIFFs
  fissa/extraction.py
  fissa/tests/test_extraction.py
Labels: bug

#182 DOC: Add elastic search on readthedocs
  docs/conf.py
  requirements_docs.txt
Labels: doc

#183 DOC: Change theme to pydata
  docs/conf.py
  requirements_docs.txt
Labels: doc

#184 DOC: Add a redirect from gh-pages base to readthedocs
  .github/workflows/gh-pages.yaml
Labels: ci, doc

#180 JNB: Blacken notebooks
  .pre-commit-config.yaml
  examples/Basic usage.ipynb
  examples/SIMA example.ipynb
  examples/Suite2p example.ipynb
  examples/cNMF example.ipynb
Labels: doc

#177 RF+ENH+BUG: Use npz for cache; store means
  fissa/core.py
  fissa/tests/base_test.py
  fissa/tests/test_core.py
  fissa/tests/test_roitools.py
Labels: bug, enhancement, vX.Y.0 New Minor Release

#179 ENH: Lazy tifffile
  fissa/core.py
  fissa/extraction.py
  fissa/tests/base_test.py
  fissa/tests/test_core.py
  fissa/tests/test_extraction.py
Labels: enhancement

#189 CI: Add .codecov.yml to allow small decreases in coverage
  .codecov.yml
Labels: ci

#192 MNT: Change separator _ to - in requirement.txt filenames
  .travis.yml
  docs/requirements.txt
  requirements-docs.txt
  requirements-plots.txt
  setup.py
Labels: maint

#191 RF: Use Mixin class for extraction tests
  fissa/tests/test_extraction.py
Labels: maint

#190 CI: Report notebook coverage
  .appveyor.yml
  .github/workflows/test-release-candidate.yaml
  .github/workflows/test.yaml
Labels: ci

#193 DOC: Update intersphinx mappings
  docs/conf.py
Labels: doc

#194 DOC: Graceful degradation of sphinx theme
  docs/conf.py
Labels: doc

#195 CI:GHA: Always run tests, don't skip based on content
  .github/workflows/test.yaml
Labels: ci

#186 RF: Don't do init as list of strings
  fissa/core.py
  fissa/roitools.py
Labels: maint

#197 TST: Test matfile output
  fissa/tests/test_core.py
Labels: test

#199 BUG: Saving and loading None values
  fissa/core.py
  fissa/tests/test_core.py
Labels: bug, test

#201 TST:RF: Move common core test operations into helper methods
  fissa/tests/base_test.py
  fissa/tests/test_core.py
Labels: maint, test

#169 ENH+API: Add functional interface
  README.rst
  examples/Basic usage - Functional.ipynb
  examples/Basic usage.ipynb
  examples/basic_usage.py
  examples/basic_usage_func.py
  examples/basic_usage_func_windows.py
  examples/basic_usage_windows.py
  fissa/__init__.py
  fissa/__meta__.py
  fissa/core.py
  fissa/tests/test_core.py
Labels: enhancement, vX.0.0 New Major Release

#202 TST: Extend core tests
  fissa/tests/generate_downsampled_resources.py
  fissa/tests/resources/a/images/AVG_A01_R1_small.tif
  fissa/tests/resources/a/rois.zip
  fissa/tests/resources/a/rois/01.roi
  fissa/tests/resources/b/expected_py2.npz
  fissa/tests/resources/b/expected_py3.npz
  fissa/tests/resources/b/images/AVG_A01.tif
  fissa/tests/resources/b/images/AVG_A02.tif
  fissa/tests/resources/b/images/AVG_A03.tif
  fissa/tests/resources/b/rois.zip
  fissa/tests/resources/b/rois/03.roi
  fissa/tests/resources/b/rois/04.roi
  fissa/tests/test_core.py
Labels: test

#204 DOC: Improve core docstrings
  docs/conf.py
  fissa/core.py
  fissa/neuropil.py
  fissa/roitools.py
  requirements-docs.txt
Labels: doc

#206 MNT: Raise an error when both lowmemory mode and manual datahandler are set
  fissa/core.py
  fissa/tests/test_core.py
Labels: maint

#207 DOC: Add note about deltaf_result baseline
  fissa/core.py
Labels: doc

#208 MNT: Move self.clear to top of init
  fissa/core.py
Labels: maint

#209 ENH: Add __repr__ and __str__ methods
  fissa/core.py
  fissa/extraction.py
  fissa/tests/test_core.py
  fissa/tests/test_extraction.py
Labels: enhancement

#187 RF: Migrate duplicated rois2masks code to function in roitools
  fissa/extraction.py
  fissa/roitools.py
  fissa/tests/test_extraction.py
Labels: maint

#188 RF: Refactor neuropil.separate
  fissa/neuropil.py
  fissa/tests/test_neuropil.py
Labels: maint

#210 DOC+BUG: Missing : separator on readthedocs
  requirements-docs.txt
Labels: bug, doc

#203 RF: Change pool functions to take keyword arguments
  fissa/core.py
  fissa/extraction.py
  fissa/tests/test_core.py
Labels: maint

#211 TST:MNT: Ignore ConvergenceWarning when intentionally not converging
  fissa/tests/test_neuropil.py
Labels: maint, test

#212 MNT: Init arrays with np.empty, dtype=object instead lists of None
  fissa/core.py
Labels: maint

#213 MNT: Fix deprecated np.float
  fissa/readimagejrois.py
Labels: maint

#214 DOC: Fix docstrings
  fissa/core.py
Labels: doc

#215 STY: Change code style to black
  .pre-commit-config.yaml
  README.rst
  docs/conf.py
  docs/source/user-guide.rst
  examples/basic_usage.py
  examples/basic_usage_func.py
  examples/basic_usage_func_windows.py
  examples/basic_usage_windows.py
  examples/datahandler_custom.py
  fissa/ROI.py
  fissa/__init__.py
  fissa/__meta__.py
  fissa/core.py
  fissa/deltaf.py
  fissa/extraction.py
  fissa/readimagejrois.py
  fissa/roitools.py
  fissa/tests/base_test.py
  fissa/tests/generate_downsampled_resources.py
  fissa/tests/generate_tiffs.py
  fissa/tests/test_ROI.py
  fissa/tests/test_core.py
  fissa/tests/test_deltaf.py
  fissa/tests/test_extraction.py
  fissa/tests/test_neuropil.py
  fissa/tests/test_readimagejrois.py
  fissa/tests/test_roitools.py
  requirements-dev.txt
  setup.py
Labels: maint

#217 DEV: Fix flake8 issues and add pre-commit
  .flake8
  .pre-commit-config.yaml
  docs/conf.py
  examples/datahandler_custom.py
  fissa/ROI.py
  fissa/deltaf.py
  fissa/readimagejrois.py
  fissa/roitools.py
  fissa/tests/base_test.py
  fissa/tests/generate_downsampled_resources.py
  fissa/tests/test_ROI.py
  fissa/tests/test_core.py
  fissa/tests/test_extraction.py
  fissa/tests/test_neuropil.py
  fissa/tests/test_roitools.py
  setup.py
Labels: maint

#218 DOC: Don't mention Py 3 requirement in _parse_roi_file_py3
  fissa/readimagejrois.py
Labels: doc

#219 API: Rename module ROI -> polygons
  CREDITS.rst
  fissa/polygons.py
  fissa/roitools.py
  fissa/tests/test_polygons.py
Labels: vX.Y.0 New Minor Release

#198 API: Change the shape of deltaf_raw to have the same number of dimensions as other outputs
  examples/Basic usage.ipynb
  fissa/core.py
  fissa/tests/resources/b/expected_py2.npz
  fissa/tests/resources/b/expected_py3.npz
  fissa/tests/test_core.py
Labels: vX.Y.0 New Minor Release
